development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_app_development 
  pool: 5
  username: <%= ENV['TODO_LIST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['TODO_LIST_APP_MYSQL_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_app_test
  pool: 5
  username: <%= ENV['TODO_LIST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['TODO_LIST_APP_MYSQL_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todo_app_production
  pool: 5
  username: <%= ENV['TODO_LIST_APP_MYSQL_USERNAME'] %>
  password: <%= ENV['TODO_LIST_APP_MYSQL_PASSWORD'] %>
